all: prob1 prob2 prob3

prob1:
	gcc cscd340_f12_lab4prob1.c -lpthread -o prob1

prob2:
	gcc cscd340_f12_lab4prob2.c -lpthread  -o prob2

prob3:
	gcc cscd340_f12_lab4prob3.c -lpthread -o prob3

clean:
	rm prob*